// SPDX-License-Identifier: GPL-3.0-or-later

/// @title Shatter Creator V1
/// @author Transient Labs 

pragma solidity ^0.8.9;

import "OpenZeppelin/openzeppelin-contracts@4.6.0/contracts/proxy/ERC1967/ERC1967Proxy.sol";

interface ShatterRegistry {
    function register(address _deployer, uint256 _version, bytes32 _nonce, bytes memory _sig) external virtual;
}

contract ShatterCreatorV1 is ERC1967Proxy {

    /// @param _sig is the trusted signature to log this as a valid Shatter contract in the Shatter registry
    /// @param _nonce is the nonce generated by the trusted signer when deploying
    /// @param _name is the name of the contract and piece
    /// @param _symbol is the symbol
    /// @param _royaltyRecipient is the royalty recipient
    /// @param _royaltyPercentage is the royalty percentage to set
    /// @param _minShatters is the minimum number of replicates
    /// @param _maxShatters is the maximum number of replicates
    /// @param _shatterTime is time after which replication can occur
    constructor(bytes memory _sig, bytes32 _nonce, string memory _name, string memory _symbol,
        address _royaltyRecipient, uint256 _royaltyPercentage,
        uint256 _minShatters, uint256 _maxShatters, uint256 _shatterTime)
        ERC1967Proxy(0x3fca9Ff8E92EE202AB541290bFb8aA143052ef0F, abi.encodeWithSignature(
            "initialize(string,string,address,uint256,uint256,uint256,uint256)",
            _name, _symbol, _royaltyRecipient, _royaltyPercentage,  _minShatters, _maxShatters, _shatterTime))
        {
            ShatterRegistry(0xFa72C510E819cA0C142Ce91973fC2f0739148dEC).register(msg.sender, 1, _nonce, _sig);
        }
}